;; Minimal Smart Contract
(define-constant contract-owner tx-sender)
(define-constant err-owner-only (err u100))
(define-data-var nonce uint u0)
(define-map records uint {owner: principal, data: (string-ascii 100), created: uint})
(define-read-only (get-record (id uint)) (map-get? records id))
(define-read-only (get-total) (var-get nonce))
(define-public (create-record (data (string-ascii 100)))
  (let ((id (+ (var-get nonce) u1)))
    (map-set records id {owner: tx-sender, data: data, created: stacks-block-height})
    (var-set nonce id)
    (ok id)))
(define-public (update-record (id uint) (data (string-ascii 100)))
  (let ((record (unwrap! (map-get? records id) (err u101))))
    (asserts! (is-eq tx-sender (get owner record)) (err u102))
    (map-set records id (merge record {data: data}))
    (ok true)))
